[project]
name = "airplane_simple-chatbot"
version = "0.0.1"
description = "a simple airplane chatbot"
author = "parsa"

[observability]
type = "phoenix"
host_type = "local"

[ml]
type = "llm"
provider = "litellm"

[ml.litellm]
model = "openai/gpt-4o"
temperature = 0.0
max_tokens = 2000
top_p = 1.0
top_k = 5

[project.dependencies.airplane_simple_retriever]
name = "airplane_simple_retriever"
directory = "./.appdeps/airplane_simple_retriever"
local = true
